# coding: utf-8

"""
    tradewatch.io

    Financial market data for Developers

    The version of the OpenAPI document: 3.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tradewatch.api.crypto_api import CryptoApi


class TestCryptoApi(unittest.TestCase):
    """CryptoApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CryptoApi()

    def tearDown(self) -> None:
        pass

    def test_convert(self) -> None:
        """Test case for convert

        Conversion
        """
        pass

    def test_crypto_get_exchanges(self) -> None:
        """Test case for crypto_get_exchanges

        Available Exchanges
        """
        pass

    def test_getQuote(self) -> None:
        """Test case for getQuote

        Last Quote
        """
        pass

    def test_getSymbols(self) -> None:
        """Test case for getSymbols

        Available Symbols
        """
        pass


if __name__ == '__main__':
    unittest.main()
