# coding: utf-8

"""
    tradewatch.io

    Financial market data for Developers

    The version of the OpenAPI document: 3.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tradewatch.models.symbols_list_mode import SymbolsListMode

class TestSymbolsListMode(unittest.TestCase):
    """SymbolsListMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSymbolsListMode(self):
        """Test SymbolsListMode"""
        # inst = SymbolsListMode()

if __name__ == '__main__':
    unittest.main()
