# coding: utf-8

"""
    tradewatch.io

    Financial market data for Developers

    The version of the OpenAPI document: 3.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tradewatch.models.commodity_type import CommodityType

class TestCommodityType(unittest.TestCase):
    """CommodityType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommodityType(self):
        """Test CommodityType"""
        # inst = CommodityType()

if __name__ == '__main__':
    unittest.main()
