# coding: utf-8

"""
    tradewatch.io

    Financial market data for Developers

    The version of the OpenAPI document: 3.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tradewatch.models.countries_list import CountriesList

class TestCountriesList(unittest.TestCase):
    """CountriesList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CountriesList:
        """Test CountriesList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CountriesList`
        """
        model = CountriesList()
        if include_optional:
            return CountriesList(
                items = [
                    tradewatch.models.country_obj.CountryObj(
                        symbol = '', )
                    ]
            )
        else:
            return CountriesList(
                items = [
                    tradewatch.models.country_obj.CountryObj(
                        symbol = '', )
                    ],
        )
        """

    def testCountriesList(self):
        """Test CountriesList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
