# coding: utf-8

"""
    tradewatch.io

    Financial market data for Developers

    The version of the OpenAPI document: 3.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tradewatch.models.account_usage_statistics_interval import AccountUsageStatisticsInterval

class TestAccountUsageStatisticsInterval(unittest.TestCase):
    """AccountUsageStatisticsInterval unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountUsageStatisticsInterval(self):
        """Test AccountUsageStatisticsInterval"""
        # inst = AccountUsageStatisticsInterval()

if __name__ == '__main__':
    unittest.main()
