# coding: utf-8

"""
    tradewatch.io

    Financial market data for Developers

    The version of the OpenAPI document: 3.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tradewatch.models.crypto_conversion_query import CryptoConversionQuery

class TestCryptoConversionQuery(unittest.TestCase):
    """CryptoConversionQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CryptoConversionQuery:
        """Test CryptoConversionQuery
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CryptoConversionQuery`
        """
        model = CryptoConversionQuery()
        if include_optional:
            return CryptoConversionQuery(
                var_from = '',
                to = '',
                amount = 1.0E-8,
                precision = 56
            )
        else:
            return CryptoConversionQuery(
                var_from = '',
                to = '',
        )
        """

    def testCryptoConversionQuery(self):
        """Test CryptoConversionQuery"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
