# coding: utf-8

"""
    tradewatch.io

    Financial market data for Developers

    The version of the OpenAPI document: 3.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tradewatch.models.error_response_body import ErrorResponseBody

class TestErrorResponseBody(unittest.TestCase):
    """ErrorResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ErrorResponseBody:
        """Test ErrorResponseBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ErrorResponseBody`
        """
        model = ErrorResponseBody()
        if include_optional:
            return ErrorResponseBody(
                error = tradewatch.models.error_details.ErrorDetails(
                    code = 56, 
                    message = '', )
            )
        else:
            return ErrorResponseBody(
                error = tradewatch.models.error_details.ErrorDetails(
                    code = 56, 
                    message = '', ),
        )
        """

    def testErrorResponseBody(self):
        """Test ErrorResponseBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
