# coding: utf-8

"""
    tradewatch.io

    Financial market data for Developers

    The version of the OpenAPI document: 3.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tradewatch.api.commodities_api import CommoditiesApi


class TestCommoditiesApi(unittest.TestCase):
    """CommoditiesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CommoditiesApi()

    def tearDown(self) -> None:
        pass

    def test_getQuote(self) -> None:
        """Test case for getQuote

        Last Quote
        """
        pass

    def test_getSymbols(self) -> None:
        """Test case for getSymbols

        Available Symbols
        """
        pass

    def test_getTypes(self) -> None:
        """Test case for getTypes

        Available Types
        """
        pass


if __name__ == '__main__':
    unittest.main()
