# coding: utf-8

"""
    tradewatch.io

    Financial market data for Developers

    The version of the OpenAPI document: 3.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tradewatch.models.cursor_page_t_customized_symbols_out_full import CursorPageTCustomizedSymbolsOutFull

class TestCursorPageTCustomizedSymbolsOutFull(unittest.TestCase):
    """CursorPageTCustomizedSymbolsOutFull unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CursorPageTCustomizedSymbolsOutFull:
        """Test CursorPageTCustomizedSymbolsOutFull
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CursorPageTCustomizedSymbolsOutFull`
        """
        model = CursorPageTCustomizedSymbolsOutFull()
        if include_optional:
            return CursorPageTCustomizedSymbolsOutFull(
                items = [
                    tradewatch.models.symbols_out_full.SymbolsOutFull(
                        symbol = '', 
                        name = '', )
                    ],
                total = 56,
                current_page = '',
                current_page_backwards = '',
                previous_page = '',
                next_page = ''
            )
        else:
            return CursorPageTCustomizedSymbolsOutFull(
                items = [
                    tradewatch.models.symbols_out_full.SymbolsOutFull(
                        symbol = '', 
                        name = '', )
                    ],
        )
        """

    def testCursorPageTCustomizedSymbolsOutFull(self):
        """Test CursorPageTCustomizedSymbolsOutFull"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
