# coding: utf-8

"""
    tradewatch.io

    Financial market data for Developers

    The version of the OpenAPI document: 3.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tradewatch.api.stocks_api import StocksApi


class TestStocksApi(unittest.TestCase):
    """StocksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StocksApi()

    def tearDown(self) -> None:
        pass

    def test_getCountries(self) -> None:
        """Test case for getCountries

        Available Countries
        """
        pass

    def test_getQuote(self) -> None:
        """Test case for getQuote

        Last Quote
        """
        pass

    def test_getSymbols(self) -> None:
        """Test case for getSymbols

        Available Symbols
        """
        pass


if __name__ == '__main__':
    unittest.main()
