# coding: utf-8

"""
    tradewatch.io

    Financial market data for Developers

    The version of the OpenAPI document: 3.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tradewatch.models.last_quote import LastQuote

class TestLastQuote(unittest.TestCase):
    """LastQuote unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LastQuote:
        """Test LastQuote
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LastQuote`
        """
        model = LastQuote()
        if include_optional:
            return LastQuote(
                symbol = '',
                ask = 1.23456,
                bid = 1.23456,
                mid = 1.23456,
                timestamp = 1704882030
            )
        else:
            return LastQuote(
                symbol = '',
                ask = 1.23456,
                bid = 1.23456,
                mid = 1.23456,
                timestamp = 1704882030,
        )
        """

    def testLastQuote(self):
        """Test LastQuote"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
