# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.account_usage_statistics_input import AccountUsageStatisticsInput
from ..types.account_usage_statistics_interval import AccountUsageStatisticsInterval


class RawAccountClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def get_usage(
        self,
        *,
        limit: typing.Optional[int] = None,
        interval: typing.Optional[AccountUsageStatisticsInterval] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[AccountUsageStatisticsInput]:
        """
        Get the usage statistics of your API account

        Parameters
        ----------
        limit : typing.Optional[int]
            The number of data points to return (max 168).

        interval : typing.Optional[AccountUsageStatisticsInterval]
            The time interval for the usage statistics.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[AccountUsageStatisticsInput]
            Success
        """
        _response = self._client_wrapper.httpx_client.request(
            "usage",
            method="GET",
            params={
                "limit": limit,
                "interval": interval,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AccountUsageStatisticsInput,
                    parse_obj_as(
                        type_=AccountUsageStatisticsInput,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawAccountClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def get_usage(
        self,
        *,
        limit: typing.Optional[int] = None,
        interval: typing.Optional[AccountUsageStatisticsInterval] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[AccountUsageStatisticsInput]:
        """
        Get the usage statistics of your API account

        Parameters
        ----------
        limit : typing.Optional[int]
            The number of data points to return (max 168).

        interval : typing.Optional[AccountUsageStatisticsInterval]
            The time interval for the usage statistics.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[AccountUsageStatisticsInput]
            Success
        """
        _response = await self._client_wrapper.httpx_client.request(
            "usage",
            method="GET",
            params={
                "limit": limit,
                "interval": interval,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AccountUsageStatisticsInput,
                    parse_obj_as(
                        type_=AccountUsageStatisticsInput,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
