# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class CryptoConversionQuery(UniversalBaseModel):
    from_: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="from"),
        pydantic.Field(alias="from", description="The symbol you want to convert from."),
    ]
    to: str = pydantic.Field()
    """
    The symbol you want to convert to.
    """

    amount: typing.Optional[float] = pydantic.Field(default=None)
    """
    The amount to be converted.
    """

    precision: typing.Optional[int] = pydantic.Field(default=None)
    """
    The decimal precision of the result.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
