# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .symbols_out_full import SymbolsOutFull


class CursorPageTCustomizedSymbolsOutFull(UniversalBaseModel):
    items: typing.List[SymbolsOutFull]
    total: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total items
    """

    current_page: typing.Optional[str] = pydantic.Field(default=None)
    """
    Cursor to refetch the current page
    """

    current_page_backwards: typing.Optional[str] = pydantic.Field(default=None)
    """
    Cursor to refetch the current page starting from the last item
    """

    previous_page: typing.Optional[str] = pydantic.Field(default=None)
    """
    Cursor for the previous page
    """

    next_page: typing.Optional[str] = pydantic.Field(default=None)
    """
    Cursor for the next page
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
