# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class HistoricalOhlcCandle(UniversalBaseModel):
    time: int
    open_ask: float
    high_ask: float
    low_ask: float
    close_ask: float
    open_bid: float
    high_bid: float
    low_bid: float
    close_bid: float

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
