# This file was auto-generated by Fern from our API Definition.

import typing

HistoricalDataResolution = typing.Union[
    typing.Literal["5", "10", "30", "60", "600", "1800", "3600", "14400", "43200", "86400"], typing.Any
]
