# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class LastQuote(UniversalBaseModel):
    symbol: str = pydantic.Field()
    """
    Symbol name
    """

    ask: float = pydantic.Field()
    """
    The ask price.
    """

    bid: float = pydantic.Field()
    """
    The bid price.
    """

    mid: float = pydantic.Field()
    """
    The mid price.
    """

    timestamp: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
