# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SymbolsOutFullStocks(UniversalBaseModel):
    symbol: str = pydantic.Field()
    """
    The unique symbol of the financial instrument (e.g. AAPL, BTCUSD, etc.).
    """

    name: str = pydantic.Field()
    """
    The full name of the financial instrument.
    """

    country: str = pydantic.Field()
    """
    The country where the stock is listed.
    """

    description: str = pydantic.Field()
    """
    The stock description.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
