# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class TradingHoursResponse(UniversalBaseModel):
    mic: str = pydantic.Field()
    """
    Market Identifier Code (ISO 10383)
    """

    date: str = pydantic.Field()
    """
    Date of the trading session (YYYY-MM-DD)
    """

    day_of_week: str = pydantic.Field()
    """
    Day of the week
    """

    is_early_close: bool = pydantic.Field()
    """
    Whether the market closes early on this day
    """

    open_time: dt.datetime = pydantic.Field()
    """
    Opening time for the day
    """

    close_time: dt.datetime = pydantic.Field()
    """
    Closing time for the day
    """

    holiday_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name of the holiday if applicable
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
