# coding: utf-8

"""
    tradewatch.io

    Financial market data for Developers

    The version of the OpenAPI document: 3.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AccountUsageStatisticsInterval(str, Enum):
    """
    Data interval
    """

    """
    allowed enum values
    """
    ENUM_1H = '1h'
    ENUM_1D = '1d'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AccountUsageStatisticsInterval from a JSON string"""
        return cls(json.loads(json_str))


