# coding: utf-8

"""
    tradewatch.io

    Financial market data for Developers

    The version of the OpenAPI document: 3.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CommodityType(str, Enum):
    """
    CommodityType
    """

    """
    allowed enum values
    """
    AGRICULTURAL = 'agricultural'
    ENERGY = 'energy'
    METAL = 'metal'
    ALL = 'all'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CommodityType from a JSON string"""
        return cls(json.loads(json_str))


