# coding: utf-8

"""
    tradewatch.io

    Financial market data for Developers

    The version of the OpenAPI document: 3.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Country(str, Enum):
    """
    The country associated with the symbol (see ISO 3166-1 alpha-2)
    """

    """
    allowed enum values
    """
    FR = 'fr'
    US = 'us'
    DE = 'de'
    NZ = 'nz'
    NL = 'nl'
    UK = 'uk'
    ES = 'es'
    CN = 'cn'
    CH = 'ch'
    GR = 'gr'
    BE = 'be'
    PT = 'pt'
    IT = 'it'
    ALL = 'all'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Country from a JSON string"""
        return cls(json.loads(json_str))


