# coding: utf-8

"""
    tradewatch.io

    Financial market data for Developers

    The version of the OpenAPI document: 3.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from tradewatch.models.symbols_out_full import SymbolsOutFull
from typing import Optional, Set
from typing_extensions import Self

class CursorPageTCustomizedSymbolsOutFull(BaseModel):
    """
    CursorPageTCustomizedSymbolsOutFull
    """ # noqa: E501
    items: List[SymbolsOutFull]
    total: Optional[StrictInt] = None
    current_page: Optional[StrictStr] = None
    current_page_backwards: Optional[StrictStr] = None
    previous_page: Optional[StrictStr] = None
    next_page: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["items", "total", "current_page", "current_page_backwards", "previous_page", "next_page"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CursorPageTCustomizedSymbolsOutFull from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in items (list)
        _items = []
        if self.items:
            for _item_items in self.items:
                if _item_items:
                    _items.append(_item_items.to_dict())
            _dict['items'] = _items
        # set to None if total (nullable) is None
        # and model_fields_set contains the field
        if self.total is None and "total" in self.model_fields_set:
            _dict['total'] = None

        # set to None if current_page (nullable) is None
        # and model_fields_set contains the field
        if self.current_page is None and "current_page" in self.model_fields_set:
            _dict['current_page'] = None

        # set to None if current_page_backwards (nullable) is None
        # and model_fields_set contains the field
        if self.current_page_backwards is None and "current_page_backwards" in self.model_fields_set:
            _dict['current_page_backwards'] = None

        # set to None if previous_page (nullable) is None
        # and model_fields_set contains the field
        if self.previous_page is None and "previous_page" in self.model_fields_set:
            _dict['previous_page'] = None

        # set to None if next_page (nullable) is None
        # and model_fields_set contains the field
        if self.next_page is None and "next_page" in self.model_fields_set:
            _dict['next_page'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CursorPageTCustomizedSymbolsOutFull from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "items": [SymbolsOutFull.from_dict(_item) for _item in obj["items"]] if obj.get("items") is not None else None,
            "total": obj.get("total"),
            "current_page": obj.get("current_page"),
            "current_page_backwards": obj.get("current_page_backwards"),
            "previous_page": obj.get("previous_page"),
            "next_page": obj.get("next_page")
        })
        return _obj


